# Generated by Django 6.0.6 on 2026-06-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnvcaWeatherInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=60, null=True
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, db_column="Province", max_length=25, null=True
                    ),
                ),
                (
                    "climate_id",
                    models.CharField(
                        blank=True,
                        db_column="Climate ID",
                        max_length=12,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "station_id",
                    models.IntegerField(blank=True, db_column="Station ID", null=True),
                ),
                (
                    "wmo_id",
                    models.IntegerField(blank=True, db_column="WMO ID", null=True),
                ),
                (
                    "tc_id",
                    models.CharField(
                        blank=True, db_column="TC ID", max_length=12, null=True
                    ),
                ),
                (
                    "latitude_decimal_degrees_field",
                    models.FloatField(
                        blank=True, db_column="Latitude (Decimal Degrees)", null=True
                    ),
                ),
                (
                    "longitude_decimal_degrees_field",
                    models.FloatField(
                        blank=True, db_column="Longitude (Decimal Degrees)", null=True
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, db_column="Latitude", null=True),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, db_column="Longitude", null=True),
                ),
                (
                    "elevation_m_field",
                    models.FloatField(blank=True, db_column="Elevation (m)", null=True),
                ),
                (
                    "first_year",
                    models.IntegerField(blank=True, db_column="First Year", null=True),
                ),
                (
                    "last_year",
                    models.IntegerField(blank=True, db_column="Last Year", null=True),
                ),
                (
                    "hly_first_year",
                    models.IntegerField(
                        blank=True, db_column="HLY First Year", null=True
                    ),
                ),
                (
                    "hly_last_year",
                    models.IntegerField(
                        blank=True, db_column="HLY Last Year", null=True
                    ),
                ),
                (
                    "dly_first_year",
                    models.IntegerField(
                        blank=True, db_column="DLY First Year", null=True
                    ),
                ),
                (
                    "dly_last_year",
                    models.IntegerField(
                        blank=True, db_column="DLY Last Year", null=True
                    ),
                ),
                (
                    "mly_first_year",
                    models.IntegerField(
                        blank=True, db_column="MLY First Year", null=True
                    ),
                ),
                (
                    "mly_last_year",
                    models.IntegerField(
                        blank=True, db_column="MLY Last Year", null=True
                    ),
                ),
            ],
            options={
                "db_table": "envca_weather_inventory",
                "managed": False,
            },
        ),
    ]
